# Generated by Django 4.0.4 on 2022-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignalReportApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalreport',
            name='bearish',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='signalreport',
            name='brief',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='signalreport',
            name='bullish',
            field=models.TextField(null=True),
        ),
    ]
